#!/bin/sh
################################################################################
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
################################################################################
# strings for test tools
# HTML_CHARSET : HTML charset
# TEST_STRING : test string
# TEST_STRING_SED : test string includes sed escapes('\')
# TEST_STRINGS : test strings(multiple)
# TEST_STRINGS_SED : test strings includes sed escapes('\')

export HTML_CHARSET="ISO8859-1"
export TEST_STRING="TEST_STRING"
export TEST_STRING_SED="TEST_STRING"
export TEST_STRINGS="TEST test Test /\!?@*#$%&~| (){}[];: "
export TEST_STRINGS_SED="TEST test Test \/\\\!\?@\*#$%\&\~| (){}[];: "
