#!/bin/ksh
# strings for test tools
# HTML_CHARSET : HTML charset
# TEST_STRING : test string
# TEST_STRING_SED : test string includes sed escapes('\')
# TEST_STRINGS : test strings(multiple)
# TEST_STRINGS_SED : test strings includes sed escapes('\')

export HTML_CHARSET="ISO8859-1"
export TEST_STRING="TEST_STRING"
export TEST_STRING_SED="TEST_STRING"
export TEST_STRINGS="TEST test Test /\!?@*#$%&~| (){}[];: "
export TEST_STRINGS_SED="TEST test Test \/\\\!\?@\*#$%\&\~| (){}[];: "
